dist: focal

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - wget
      - pkg-config

cache:
  directories:
    - $HOME/.cache/apt

before_install:
  - echo "Installing C++ and Python"
  - sudo apt-get update && sudo apt-get install -y --no-install-recommends --no-install-suggests build-essential g++ python-dev python3-dev python3-pip libc-dev python3-venv openmpi-bin libopenmpi-dev libomp-dev lammps
  - sudo apt-get install gsl-bin libgsl0-dev libboost-all-dev imagemagick-6.q16 inkscape
  - cp /var/cache/apt/archives/*.deb $HOME/.cache/apt/
  - export BOOST_LIBDIR=/usr/lib/x86_64-linux-gnu/
  - rm Gemfile.lock

jobs:
  include:
    - stage: test
      script:
        - sed -i 's/%use/#%use/' bin/nanobind-frontend.ipynb
        - sed -i 's/import hublib.use/#import hublib.use/' bin/nanobind-frontend.ipynb
        - sed -i 's/0000/000/' bin/infiles/in.lammps.template
        - sed -i 's/lmp_g++/lmp/' bin/Makefile
        - make all
        - cd bin && ./test.sh
      name: test
